name: rapid_aid_app
description: A safety app for emergency services
version: 1.0.0
environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  cloud_functions: ^5.0.0
  get: ^4.6.6
  shared_preferences: ^2.3.0
  uuid: ^4.5.0
  flutter_lints: ^2.0.0
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.3.0
  twilio_flutter: ^0.9.0
  http: ^1.2.0
  flutter_dotenv: ^5.2.1
  # geolocator: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/data/mock_contacts.json
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700