// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0ZfGpMDsOTlCCBoe9X4W8f3NmitOvvQY',
    appId: '1:1020446016092:web:86d04fae5abb0120711c99',
    messagingSenderId: '1020446016092',
    projectId: 'rapidaid-2b03e',
    authDomain: 'rapidaid-2b03e.firebaseapp.com',
    storageBucket: 'rapidaid-2b03e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOQaT1DzgyYCQ0k5_WRHaBnnMMO-3R9vs',
    appId: '1:1020446016092:android:99b6ec007fb67344711c99',
    messagingSenderId: '1020446016092',
    projectId: 'rapidaid-2b03e',
    storageBucket: 'rapidaid-2b03e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHF1pwDl7qn1SiikDtgbY5Gxrg-HcNvWI',
    appId: '1:1020446016092:ios:7d0dabbfcf4c2175711c99',
    messagingSenderId: '1020446016092',
    projectId: 'rapidaid-2b03e',
    storageBucket: 'rapidaid-2b03e.firebasestorage.app',
    iosBundleId: 'com.example.rapidAidApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHF1pwDl7qn1SiikDtgbY5Gxrg-HcNvWI',
    appId: '1:1020446016092:ios:7d0dabbfcf4c2175711c99',
    messagingSenderId: '1020446016092',
    projectId: 'rapidaid-2b03e',
    storageBucket: 'rapidaid-2b03e.firebasestorage.app',
    iosBundleId: 'com.example.rapidAidApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0ZfGpMDsOTlCCBoe9X4W8f3NmitOvvQY',
    appId: '1:1020446016092:web:080aea4a50674730711c99',
    messagingSenderId: '1020446016092',
    projectId: 'rapidaid-2b03e',
    authDomain: 'rapidaid-2b03e.firebaseapp.com',
    storageBucket: 'rapidaid-2b03e.firebasestorage.app',
  );
}
