import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure
import 'constants/theme.dart';
import 'providers/auth_provider.dart';
import 'providers/contact_provider.dart';
import 'providers/location_provider.dart';
import 'providers/service_provider.dart';
import 'screens/auth/login_screen.dart';
import 'screens/intro_screen.dart';
import 'services/twilio_service.dart'; // Import TwilioService
import 'package:flutter_dotenv/flutter_dotenv.dart';
void main() async {
  // Ensure Flutter is initialized before Firebase
  WidgetsFlutterBinding.ensureInitialized();
  await dotenv.load(fileName: ".env");
  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Initialize Twilio
  await TwilioService.initializeTwilio();

  // Initialize providers
  Get.put(AuthProvider());
  Get.put(ContactProvider());
  Get.put(LocationProvider());
  Get.put(ServiceProvider());

  runApp(const RapidAidApp());
}

class RapidAidApp extends StatelessWidget {
  const RapidAidApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Obx(
      () => GetMaterialApp(
        title: 'Rapid Aid',
        theme: Get.find<AuthProvider>().isDarkMode ? darkTheme : lightTheme,
        home: Get.find<AuthProvider>().isFirstInstall
            ? const IntroScreen()
            : const LoginScreen(),
        debugShowCheckedModeBanner: false,
      ),
    );
  }
}
